AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: queue1234567
  EntryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EntryTable
      AttributeDefinitions:
        - AttributeName: ImageName
          AttributeType: S
      KeySchema:
        - AttributeName: ImageName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamEnabled: true
        StreamViewType: NEW_IMAGE
  VehicleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VehicleTable
      AttributeDefinitions:
        - AttributeName: VehicleID
          AttributeType: S
        - AttributeName: Whitelisted
          AttributeType: BOOL
      KeySchema:
        - AttributeName: VehicleID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SQSTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: process-image-function
      Runtime: python3.8
      Handler: lambda_handler.lambda_handler
      Code:
        S3Bucket: storefunctionszip
        S3Key: lambda_handler.zip
      Role: arn:aws:iam::numero-de-compte:role/process-image-role
      Events:
        SQSEvent:
          Type: AWS::Lambda::EventSourceMapping
          Properties:
            BatchSize: 10
            EventSourceArn: !GetAtt Queue.Arn
            FunctionName: !Ref process-image-function
  DynamoDBTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: send-notification-function
      Runtime: python3.8
      Handler: lambda_handler.lambda_handler
      Code:
        S3Bucket: storefunctionszip
        S3Key: lambda_handler2.zip
      Role: arn:aws:iam::numero-de-compte:role/send-notification-role
      Events:
        DynamoDBEvent:
          Type: AWS::Lambda::EventSourceMapping
          Properties:
            BatchSize: 100
            EventSourceArn: !GetAtt EntryTable.StreamArn
            FunctionName: !Ref send-notification-function
            StartingPosition: TRIM_HORIZON